# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MIDIchlorians' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master', :submodules => true  
  pod 'SwiftLint'
  # Pods for MIDIchlorians

  target 'MIDIchloriansUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

