# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MIDIchlorians' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master', :submodules => true  
  pod 'SwiftLint'
  pod 'SnapKit', '~> 3.2.0'
  # Pods for MIDIchlorians

  target 'MIDIchloriansTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
    pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master', :submodules => true
  end

  target 'MIDIchloriansUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

